# 测试
## 普通值（字面量）
date: 2024/1/31
key: 123456789

## 对象/map
student:
  name: xy
  age: 11

# 整合mybatis配置数据库信息
spring:
  datasource:
    url: jdbc:mysql://localhost:9090/mybatis?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: sy20021213
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml  # mapper映射文件路径
  type-aliases-package: org/example/domain  # 配置哪个包下的类有默认别名

